### ISSUE TITLE
unrecognized PostgreSQL field type uuid (id:2950)

### ISSUE THREAD

**Issue by koseri** [rstats-db/RPostgres#30]
Connecting to a table with field type uuid generates a warning.

###  Table creation 
```SQL
CREATE TABLE prd_tv_sandbox.r_gender
(
respid UUID,
wave_id UUID,
gender INTEGER,
PRIMARY KEY (respid,wave_id)
);
```

## # The R:
```r
library (RPostgres)
library ( dplyr)
library ( DBI )


con_sb <- src_postgres(dbname = "the_db",   user = "[id]", password = "***")

gen_db <-  tbl ( con_sb, "r_gender" )
```

Warning messages:
1: In postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver warning: (unrecognized PostgreSQL field type uuid (id:2950) in column 0)
2: In postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver warning: (unrecognized PostgreSQL field type uuid (id:2950) in column 1)
```

**Comment by koseri** [comment]
BTW, if you don't have any UUIDs handy, Postgres will be glad to make them for you.

```sql
CREATE TABLE fuutab
(
fuu UUID DEFAULT uuid_generate_v4(),
name VARCHAR(255) NOT NULL
);
```

**Comment by alexfun** [comment]
Is this a problem? R doesn't have any default data types to handle uuids... I am guessing it gets converted to character().

**Comment by koseri** [comment]
It is indeed character data in R. However, as soon as you connect to or use a table with Postgres field type UUID, the driver starts throwing warnings. Incessant warnings over nothing are undesirable.

**Comment by alexfun** [comment]
But for other cases the warning is helpful. E.g. if you have the citext (case insensitive text) plug-in installed, then you have to be careful writing and downloading data from case insensitive columns.

**Comment by koseri** [comment]
The idea would be to throw warnings only for truly unrecognized types.

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by abhoffman** [comment]
+1

**Comment by mamaya881** [comment]
+1

**Comment by EmteZogaf** [comment]
+1

**Comment by JackStat** [comment]
Can someone review the pull request #55 and merge or make recommendations for modifications?  I just want the changes to be fresh if there is a discussion to be had and it seems like people would like to see a fix added.

**Comment by krlmlr** [comment]
Done. For now there's `devtools::install_github("rstats-db/RPostgres#55")`

**Comment by jnolis** [comment]
This issue was closed a long time ago, yet somehow I am still seeing this error.

```r
con <- DBI::dbConnect(RPostgreSQL::PostgreSQL(),
                 dbname =  "postgres",
                 port = 5432,
                 host = "127.0.0.1",
                 user = "postgres",
                 password = password
  )
DBI::dbSendStatement(con,"CREATE TABLE test (id UUID DEFAULT uuid_generate_v4 ());")
DBI::dbGetQuery(con,"SELECT * FROM test")
```
Yields:
```
data frame with 0 columns and 0 rows
Warning message:
In postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver warning: (unrecognized PostgreSQL field type uuid (id:2950) in column 0)
```

Any idea why it might be showing up? Thank you!

**Comment by krlmlr** [comment]
The code refers to the {RPostgreSQL} package, this repo hosts the {RPostgres} package. Do you still see the error when using {RPostgres}?

**Comment by jnolis** [comment]
Nope no issue. Sorry I didn't realize they were two separate packages!
